apiVersion: apps/v1
kind: Deployment # deployment
metadata:
  name: movielens-db
  labels:
    app: movielens-db-deploy
spec: # deployment spec
  replicas: 1
  selector:
    matchLabels:
      app: movielens-db-pod
  template: # pod template
    metadata:
      labels:
        app: movielens-db-pod
    spec: # pod
      containers:
        - name: movielens-db
          image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
          ports:
            - port: 9200
              protocol: TCP
              targetPort: 9200
            - port: 9300
              protocol: TCP
              targetPort: 9300
          env:
            name: "discovery.type"
            value: "single-node"
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service # load balancer for db
metadata:
  name: movielens-db-lb
spec:
  selector:
    app: movielens-db-pod # routing incoming traffic to backend pods
  type: LoadBalancer
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
    - port: 9300
      protocol: TCP
      targetPort: 9300
