apiVersion: apps/v1
kind: Deployment # deployment
metadata:
  name: movielens
  labels:
    app: movielens-deploy
spec: # deployment spec
  replicas: 2
  selector:
    matchLabels:
      app: movielens-pod
  template: # pod template
    metadata:
      labels:
        app: movielens-pod
    spec: # pod
      containers:
        - name: movielens
          image: roygou/movielens-backend:latest
#          readinessProbe:
#            httpGet:
#              scheme: HTTP
#              host: localhost
#              port: 8080
#              path: home
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service # load balancer
metadata:
  name: movielens-lb
spec:
  selector:
    app: movielens-pod # routing incoming traffic to backend pods
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
